filter_type: "EKF"                                              # The Kalman filter type: EKF = Extended Kalman Filter, UKF = Uncented Kalman Filter
prune_named: false                                               # make sure identity tracks are unique (prunes the one with high stdev)
std_limit: 0.3                                                   # pruning tracks that have std(x) > std_limit
cv_noise_params:                                                # The noise for the constant velocity prediction model
  x: 0.075
  y: 0.010
  z: 0.010
detectors:                                                      # Add detectors under this namespace
  default_tracker:                                       # Track all objects without using tags
    tagged_topic: "/rasberry_perception/poses/bbox"
    cartesian_noise_params:                                     # Expected noise in the poses (how good is the localisation)
      x: 0.0050
      y: 0.0025
      z: 0.0025
    observation_model: "CARTESIAN"                            # CARTESIAN will use CARTESIAN_3D by default
    matching_algorithm: "NN_LABELED"                          # The algorithm to match different detections. NN = Nearest Neighbour, NNJPDA = NN Joint Probability Data Association
    seq_size: 10                                              # Minimum `seq_size` number of detections received in `seq_time` seconds (if seq_size is 1, seq_time is not used)
    seq_time: 1.2